os: linux
language: nix
dist: xenial

branches:
  only:
  - main

install:
- nix-shell --run "make"
- nix-shell --run "make edsger"

script:
- nix-shell --run "cd unittests; ./autorun_unittests.sh"
- nix-shell --run "cd integration-tests; ./autorun_integration_tests.sh"
