(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module contract.DataTypes for contract.ds *)
Require Import BinPos.
Require Import DeepSpec.Runtime.
Require Import contract.EdsgerIdents.

Section EdsgerGen.


Definition addr := int256.

Record Transfer := {
  amount : int256;
  recipient : int256
}.

Definition list_Transfer := (list Transfer).

End EdsgerGen.
